/**
 * Brief-section renderers — one function per section of the canonical
 * agent-brief structure.
 *
 * Each function takes (config, patterns) and returns a Markdown chunk.
 * Sections that should be omitted under some configs return null so the
 * orchestrator can filter them out without emitting empty blocks.
 *
 * The chunks are later joined by `---` separators in generator.ts, then
 * run through substitute() to fill reserved placeholders like
 * {{PROJECT_NAME}} and {{DEFAULT_TENANT_ID}}.
 */
import type { AegisConfig } from '../wizard/schema.js';
import type { LoadedPattern } from '../patterns/loader.js';

// ============================================================================
// Small helpers
// ============================================================================

function patternRefList(patterns: readonly LoadedPattern[]): string {
  return patterns
    .map((p) => `${p.frontmatter.category}/${p.frontmatter.name}`)
    .join(' · ');
}

function hasLocale(config: AegisConfig, locale: string): boolean {
  return config.localization.locales.includes(locale as 'de' | 'en' | 'fr' | 'es' | 'it' | 'nl');
}

function companyInfoLine(config: AegisConfig): string {
  const addr = config.compliance.company_address;
  if (!addr) {
    return `${config.identity.company_name} · address-on-file-missing (populate in config)`;
  }
  const parts = [
    config.identity.company_name,
    addr.street,
    addr.zip_city,
    addr.country,
    addr.email,
  ].filter(Boolean);
  return parts.join(' · ');
}

function deployTargetPrettyName(target: string): string {
  switch (target) {
    case 'localhost':
      return 'Localhost-only (manual deploy later)';
    case 'vercel':
      return 'Vercel';
    case 'dokploy-hetzner':
      return 'Dokploy on Hetzner';
    case 'fly-io':
      return 'Fly.io';
    case 'railway':
      return 'Railway';
    case 'custom':
      return 'Custom (operator-configured)';
    case 'skip':
      return 'Not-yet-chosen';
    default:
      return target;
  }
}

// ============================================================================
// Section renderers
// ============================================================================

export function renderHeader(
  config: AegisConfig,
  patterns: readonly LoadedPattern[],
): string {
  const nowIso = config.generated_at;
  const locales = config.localization.locales.join(' + ').toUpperCase();
  const deploy = deployTargetPrettyName(config.deployment.target);
  const stackCore = [
    'Next.js 16',
    'TypeScript strict',
    'Tailwind CSS v4',
    'shadcn/ui',
    'Supabase',
    'Zustand',
    'TanStack Query',
    'React Hook Form',
    'Zod',
  ].join(' · ');

  return [
    `# Agent Brief: ${config.identity.project_name}`,
    '',
    `**Generated by:** AEGIS Wizard v{{AEGIS_WIZARD_VERSION}} · ${nowIso} · \`aegis-wizard new ${config.identity.project_name}\``,
    `**Project type:** ${config.identity.project_description}`,
    `**Stack:** ${stackCore}`,
    `**Selected patterns:** ${patternRefList(patterns)}`,
    `**Deployment target:** ${deploy}`,
    `**Languages:** ${locales}`,
    `**Company info:** ${companyInfoLine(config)}`,
    `**Expected post-build grade:** AEGIS-scan >= 960 / A · React-Doctor >= 93`,
  ].join('\n');
}

export function renderAgentInstructions(): string {
  return [
    '# Agent-Instructions (READ FIRST)',
    '',
    'You are a software-engineering agent (Claude Code, Codex, Cursor, or similar). You have this brief plus access to the empty project directory. Build a complete working SaaS backend following this brief top-to-bottom.',
    '',
    '## Operating rules',
    '',
    '1. **Boil the Lake** - deliver COMPLETE features. No `TODO:` markers. No "basic version first". If a file is specified, write it fully.',
    '2. **Search Before Building** - before writing any helper, grep the existing code. Multi-tenant-guard, logger, errors are all present after Phase 1.',
    '3. **Explicit-Paths** - when staging git changes, list files by name. Never `git add -A`.',
    '4. **Localhost-First** - never push to remote until local passes all quality-gates.',
    '5. **2-Checkpoint-Halt between phases** - after each phase, STOP and run gate-checks before next.',
    '6. **Defensive-execution** - if a phase takes >90min, HALT and write a handover, do NOT half-complete.',
    '',
    '## Ask vs decide',
    '',
    '**Decide autonomously:** file-names, variable-names, CSS-classes, test-names, which shadcn primitive to use.',
    '',
    '**Ask the user:** schema-changes mid-build, third-party-integrations not in this brief, any destructive git operation (reset, force-push, rm -rf).',
  ].join('\n');
}

export function renderCoreRules(config: AegisConfig): string {
  const lines: string[] = [
    '# Core Rules (non-negotiable)',
    '',
    '## Multi-Tenancy (HARD)',
    '- Every domain-table has `tenant_id uuid not null references tenants(id) on delete cascade`',
    '- Every authenticated API route calls `secureApiRouteWithTenant()` plus `requireRole()`',
    "- Every RLS policy filters by `tenant_id = (auth.jwt() ->> 'tenant_id')::uuid` or equivalent",
    '- No exception. Violating this equals an IDOR vulnerability.',
    '',
  ];

  if (hasLocale(config, 'de')) {
    lines.push(
      '## Umlaute in UI (German text only)',
      '- Use real umlauts in German UI text: ä ö ü ß',
      '- ASCII-fallbacks (ae / oe / ue / ss) only in DB-keys, URL-slugs, file-names, variable-names.',
      '- Gate: `grep -rn "Gruss\\|Raeume\\|Ueber\\|Foer\\|Pruefen" src/app src/components` must return zero.',
      '',
    );
  }

  lines.push(
    '## Zod .strict()',
    '- All POST/PATCH/PUT bodies parsed with `z.object({...}).strict()`',
    '- Unknown keys produce Zod errors (prevents mass-assignment).',
    '',
    '## Optimistic updates',
    "- Every mutation uses TanStack Query's `useMutation` with `onMutate` (optimistic-update), `onError` (rollback), and `onSettled` (invalidate).",
    '- Never show a loading-spinner for mutations - show the optimistic-state immediately.',
    '',
    '## No new dependencies without mentioning',
    '- Every `npm install <package>` not in this brief must be flagged in your phase-report.',
  );

  return lines.join('\n');
}

export function renderInstallation(
  config: AegisConfig,
  patterns: readonly LoadedPattern[],
): string {
  const hasI18n = patterns.some((p) => p.frontmatter.name === 'i18n-next-intl');
  const projectName = config.identity.project_name;

  const npmDeps = [
    '@supabase/supabase-js@latest',
    '@supabase/ssr@latest',
    'zustand@latest',
    '@tanstack/react-query@latest',
    'react-hook-form@latest',
    '@hookform/resolvers@latest',
    'zod@latest',
  ];
  if (hasI18n) npmDeps.push('next-intl@latest');

  const shadcnComponents = [
    'button input label card form alert',
    'dialog sheet drawer popover dropdown-menu',
    'table data-table',
    'avatar badge separator skeleton',
    'toast sonner progress spinner',
    'select combobox checkbox radio-group switch',
    'tabs accordion',
    'breadcrumb pagination',
    'command',
    'date-picker calendar',
  ];

  return [
    '# Installation (Phase 1 commands)',
    '',
    'Run these in order. Each step is idempotent. Stop on any non-zero exit and investigate.',
    '',
    '```bash',
    '# 1. Bootstrap Next.js',
    `npx create-next-app@latest ${projectName} \\`,
    '  --typescript --tailwind --eslint --app --src-dir \\',
    '  --no-turbopack --import-alias "@/*" --disable-git',
    `cd ${projectName}`,
    'git init',
    '',
    '# 2. Install core deps',
    'npm install \\',
    npmDeps.map((d) => `  ${d}`).join(' \\\n'),
    '',
    '# 3. Install dev-deps',
    'npm install -D \\',
    '  vitest@latest \\',
    '  @testing-library/react@latest \\',
    '  @testing-library/jest-dom@latest \\',
    '  @playwright/test@latest \\',
    '  tsx@latest',
    '',
    '# 4. Initialize Supabase CLI',
    'npx supabase init',
    '',
    '# 5. Install shadcn/ui + theme',
    'npx shadcn@latest init --force',
    '',
    '# 6. Add shadcn components',
    'npx shadcn@latest add \\',
    shadcnComponents.map((c) => `  ${c}`).join(' \\\n'),
    '```',
    '',
    'After step 6, verify:',
    '```bash',
    'ls src/components/ui/ | wc -l     # expect 30-40 components',
    'npm run build                      # expect exit 0',
    '```',
  ].join('\n');
}

export function renderDatabaseSchema(
  patterns: readonly LoadedPattern[],
): string {
  const lines: string[] = [
    '# Database Schema',
    '',
    'Create migrations in `supabase/migrations/` in this order.',
    '',
  ];

  let step = 1;
  const tenancyPat = patterns.find((p) => p.frontmatter.name === 'multi-tenant-supabase');
  if (tenancyPat) {
    lines.push(
      `## ${step}. \`00001_base_tenants_profiles.sql\``,
      '',
      `See \`docs/patterns/${tenancyPat.relativePath}\` - full SQL migration with tenants, profiles, RLS, handle_new_user trigger, touch_updated_at trigger.`,
      '',
      'Key tables created: `tenants`, `profiles`',
      'Key triggers: `on_auth_user_created`, `profiles_touch_updated_at`',
      'RLS: enabled on both; policies filter by `auth.uid()` plus role.',
      '',
    );
    step++;
  }

  const dsgvoPat = patterns.find((p) => p.frontmatter.name === 'dsgvo-kit');
  if (dsgvoPat) {
    lines.push(
      `## ${step}. \`00010_dsgvo.sql\``,
      '',
      `See \`docs/patterns/${dsgvoPat.relativePath}\` - user_consents, deletion_queue, audit_log tables with append-only trigger, process_deletion_queue procedure, RLS policies.`,
      '',
      'Key tables: `user_consents`, `deletion_queue`, `audit_log`',
      'Key procedures: `process_deletion_queue()` (pg_cron-scheduled hourly).',
      '',
    );
    step++;
  }

  lines.push(
    `## ${step}. Apply migrations`,
    '',
    '```bash',
    'npx supabase migration up',
    'npx supabase db diff   # expect empty output',
    '```',
    '',
    `## ${step + 1}. Seed default data`,
    '',
    'Create `supabase/seed.sql`:',
    '',
    '```sql',
    '-- Default tenant (for unauth-routes fallback if enabled)',
    "insert into tenants (id, name, slug, is_active)",
    "values ('{{DEFAULT_TENANT_ID}}', 'Default', 'default', true)",
    'on conflict (id) do nothing;',
    '```',
  );

  return lines.join('\n');
}

export function renderPagesInventory(config: AegisConfig): string {
  const hasLocalePrefix = config.localization.i18n_strategy === 'url-prefix';
  const prefix = hasLocalePrefix ? '/[locale]' : '';
  const hasDsgvo = config.compliance.dsgvo_kit === true;
  const legal = config.compliance.legal_pages;

  const adminPages = [
    '`/admin/dashboard` - welcome plus basic metrics tiles',
    '`/admin/mein-bereich` - profile plus preferences tabs (`/datenschutz` sub-route if DSGVO enabled)',
    '`/admin/einstellungen` - app settings (admin-only)',
    '`/admin/rechtliches` - legal-pages admin-editor (admin-only)',
  ];
  if (hasDsgvo) {
    adminPages.push('`/admin/audit-log` - view audit-log (admin-only)');
  }

  const publicPages: string[] = [
    '`/` - landing page (replace with your marketing-copy)',
  ];
  for (const p of legal) {
    publicPages.push(`\`${prefix}/${p}\` - from compliance/legal-pages-de pattern`);
  }

  const authPages = [
    '`/login`, `/signup`, `/auth/forgot-password`, `/auth/update-password`, `/auth/callback` - from foundation/auth-supabase-full pattern',
  ];

  const lines: string[] = ['# Pages Inventory', ''];
  lines.push(`Total: ${adminPages.length + publicPages.length + authPages.length} pages (saas-starter baseline). Add your branche-specific pages on top.`);
  lines.push('', '## Admin pages');
  adminPages.forEach((p) => lines.push(`- ${p}`));
  lines.push('', '## Public pages');
  publicPages.forEach((p) => lines.push(`- ${p}`));
  lines.push('', '## Auth pages');
  authPages.forEach((p) => lines.push(`- ${p}`));

  return lines.join('\n');
}

export function renderComponentCatalog(
  patterns: readonly LoadedPattern[],
): string {
  const lines: string[] = [
    '# Component Catalog',
    '',
    '## From shadcn-CLI (installed via Installation section step 6)',
    'All foundation primitives: Button, Input, Card, Dialog, Table, DataTable, etc.',
    '',
    '## From patterns in this brief',
  ];
  const dsgvoPat = patterns.find((p) => p.frontmatter.name === 'dsgvo-kit');
  if (dsgvoPat) {
    lines.push(`- \`<CookieBanner />\` - from compliance/dsgvo-kit`);
  }
  const i18nPat = patterns.find((p) => p.frontmatter.name === 'i18n-next-intl');
  if (i18nPat) {
    lines.push(`- \`<LanguageSwitcher />\` - from foundation/i18n-next-intl`);
  }
  lines.push('');
  lines.push(
    '## Project-specific (you build)',
    '- `<Sidebar />` - admin-sidebar with sections (Dashboard, Mein-Bereich, Einstellungen, Rechtliches). Use shadcn Sidebar component as base.',
    '- `<AppShell />` - layout-wrapper for admin-pages (sidebar plus header plus main).',
  );
  return lines.join('\n');
}

export function renderApiRoutes(patterns: readonly LoadedPattern[]): string {
  const lines: string[] = [
    '# API Routes',
    '',
    '## Convention (every authenticated route)',
    '',
    '```typescript',
    "import { NextRequest, NextResponse } from 'next/server';",
    "import { secureApiRouteWithTenant } from '@/lib/api/tenant-guard';",
    "import { requireRole } from '@/lib/api/require-role';",
    "import { createServerSupabaseClient } from '@/lib/supabase/server';",
    "import { logger } from '@/lib/utils/logger';",
    "import { z } from 'zod';",
    '',
    'const BodySchema = z.object({ /* fields */ }).strict();',
    '',
    'export async function POST(request: NextRequest) {',
    '  try {',
    '    const { context } = await secureApiRouteWithTenant(request, { requireAuth: true });',
    '    if (!context.userId) {',
    "      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });",
    '    }',
    "    requireRole(context, ['admin', 'manager']);",
    '',
    '    const body = BodySchema.parse(await request.json());',
    '    const supabase = await createServerSupabaseClient();',
    '',
    '    const { data, error } = await supabase',
    "      .from('<table>')",
    '      .insert({ ...body, tenant_id: context.tenantId })',
    '      .select()',
    '      .single();',
    '',
    '    if (error) {',
    "      logger.error('DB insert failed', error, { userId: context.userId });",
    "      return NextResponse.json({ error: 'Insert failed' }, { status: 500 });",
    '    }',
    '',
    '    return NextResponse.json(data);',
    '  } catch (err) {',
    '    const status = (err as { statusCode?: number }).statusCode ?? 500;',
    "    const message = err instanceof Error ? err.message : 'Internal error';",
    "    logger.error('Route failed', err as Error);",
    '    return NextResponse.json({ error: message }, { status });',
    '  }',
    '}',
    '```',
    '',
    '## Routes to create (saas-starter baseline)',
    '',
  ];

  const dsgvoPat = patterns.find((p) => p.frontmatter.name === 'dsgvo-kit');
  if (dsgvoPat) {
    lines.push(
      '- `/api/dsgvo/consent` (POST) - from compliance/dsgvo-kit',
      '- `/api/dsgvo/export` (GET) - from compliance/dsgvo-kit',
      '- `/api/dsgvo/delete` (POST) - from compliance/dsgvo-kit',
      '- `/api/admin/audit-log` (GET, admin-only) - paginated audit-log view',
    );
  }
  lines.push(
    '- `/api/admin/settings/{get,patch}` (admin-only)',
    '- `/api/admin/profile` (GET, PATCH own; PATCH others with admin-role)',
    '',
    'Add domain-specific routes on top per your project needs.',
  );

  return lines.join('\n');
}

export function renderBuildOrder(patterns: readonly LoadedPattern[]): string {
  const lines: string[] = [
    '# Build Order',
    '',
    '**Strict top-to-bottom. After each phase, run the quality-gates section. If any gate fails, halt and fix before next phase.**',
    '',
    '## Phase 1 - Foundation (~2h)',
    '1. Run all `npm install` plus `shadcn add` commands from the Installation section',
    '2. Copy foundation/multi-tenant-supabase pattern files to `src/lib/`:',
    '   - `lib/supabase/{admin,client,server}.ts`',
    '   - `lib/api/{client-ip,tenant-guard}.ts`',
    '   - `lib/utils/tenant-resolver.ts`',
    '3. Copy foundation/logger-pii-safe to `lib/utils/logger.ts`',
    '4. Copy foundation/rbac-requirerole to `lib/api/require-role.ts`',
    '5. Apply migration `00001_base_tenants_profiles.sql`',
    '6. **Gate:** `npm run build` exit 0; tests pass',
    '',
    '## Phase 2 - Middleware + Auth (~2h)',
    '1. Copy foundation/middleware-hardened to `middleware.ts`',
    '2. Copy foundation/auth-supabase-full to auth pages plus components (login, signup, forgot-password, update-password, callback)',
    '3. Create `src/app/admin/layout.tsx` with auth-check plus Sidebar wrapper',
    '4. **Gate:** Sign up new user in browser, confirm email, log in, redirect to `/admin/dashboard` works',
    '',
  ];

  if (patterns.some((p) => p.frontmatter.name === 'i18n-next-intl')) {
    lines.push(
      '## Phase 3 - i18n (~1h)',
      '1. Copy foundation/i18n-next-intl files (routing, navigation, request configs plus middleware extension plus messages JSON)',
      '2. Move all pages under `src/app/[locale]/`',
      '3. Update all hardcoded strings to use `t(\'key\')` via `useTranslations` or `getTranslations`',
      '4. **Gate:** `/de/admin/dashboard` plus `/en/admin/dashboard` both work; `LanguageSwitcher` toggles',
      '',
    );
  }

  if (patterns.some((p) => p.frontmatter.name === 'dsgvo-kit')) {
    lines.push(
      '## Phase 4 - DSGVO Kit (~2h)',
      '1. Copy compliance/dsgvo-kit files: SQL migration, CookieBanner, API routes, `/admin/mein-bereich/datenschutz` page',
      '2. Mount `<CookieBanner />` in root layout',
      '3. Apply migration `00010_dsgvo.sql`',
      '4. Configure pg_cron for `process_deletion_queue()` (see dsgvo-kit pattern Supabase-dashboard-config section)',
      '5. **Gate:** Cookie-banner shows on first-visit; `/api/dsgvo/export` downloads JSON; `/api/dsgvo/delete` schedules entry in deletion_queue',
      '',
    );
  }

  if (patterns.some((p) => p.frontmatter.name === 'legal-pages-de')) {
    lines.push(
      '## Phase 5 - Legal Pages (~1h)',
      '1. Copy compliance/legal-pages-de to `/[locale]/impressum`, `/[locale]/datenschutz`, `/[locale]/agb`',
      '2. Verify all `{{placeholders}}` are substituted (grep `{{`)',
      '3. **Gate:** Pages render without placeholder-leakage; footer-links work from all admin pages',
      '',
    );
  }

  lines.push(
    '## Phase 6 - Admin Shell (~2h)',
    '1. Build `<Sidebar />` with 5 sections (Dashboard, Mein-Bereich, Einstellungen, Rechtliches, Audit-Log if DSGVO enabled)',
    '2. Build `/admin/dashboard` stub with welcome-message plus optional 3 KPI-tiles',
    '3. Build `/admin/einstellungen` with tabs (Allgemein, Benachrichtigungen, Sicherheit)',
    '4. Build `/admin/mein-bereich` profile-page with edit-form',
    '5. Build `/admin/audit-log` admin-only list-view (if DSGVO enabled)',
    '6. **Gate:** All admin-pages accessible plus responsive; role-based visibility works',
    '',
    '## Phase 7 - Testing Scaffolding (~1h)',
    '1. Configure Vitest plus Testing-Library: `vitest.config.ts` plus `test-utils.ts`',
    '2. Configure Playwright: `playwright.config.ts` plus basic golden-path test',
    '3. Author smoke-tests per pattern (from each pattern\'s Test example section)',
    '4. **Gate:** `npm run test` plus `npm run test:e2e` both pass',
    '',
    '## Phase 8 - CI/CD (~1h)',
    '1. Create `.github/workflows/ci.yml` with checkout, setup-node, npm ci, npm run build, npm run test, npx aegis scan',
    '2. **Gate:** Commit triggers CI; build plus tests plus aegis-scan all green',
    '',
    '## Phase 9 - Deployment-Config (~1h)',
    '1. Create `Dockerfile` with node:22-alpine multi-stage build and `output: \'standalone\'` target',
    '2. Update `next.config.ts` with `output: \'standalone\'`',
    '3. Create `.dockerignore` plus `docker-compose.yml`',
    '4. Document `.env.production` checklist',
    '**Gate:** `docker build` succeeds; `docker run -p 3000:3000 <project>` renders at localhost:3000',
    '',
    '## Phase 10 - Final Verification (~30min)',
    '1. Run the FULL quality-gate-suite below',
    '2. Fix any finding',
    '3. Write `.env.example` plus `README.md` with project-specific info',
    '4. Write `POST-BUILD-REPORT.md` (per the Post-Build Report template section)',
    '5. **Gate:** All quality-gates green; user-approved handover',
  );

  return lines.join('\n');
}

export function renderQualityGates(config: AegisConfig): string {
  const lines: string[] = [
    '# Quality Gates (ALL must pass before "done")',
    '',
    'Run after each phase plus end-of-build:',
    '',
    '```bash',
    'npm run build                   # expect exit 0',
    'npx tsc --noEmit                # expect 0 errors',
    'npx next lint                   # expect 0 errors',
    'npm run test                    # expect all pass',
    'npm run test:e2e                # expect golden-path green',
    'npx aegis scan .                # expect score >= 960, grade A, 0 critical',
    'npx -y react-doctor@latest .    # expect score >= 93',
  ];

  if (hasLocale(config, 'de')) {
    lines.push(
      'grep -rn "Gruss\\|Raeume\\|Ueber\\|Foer\\|Pruefen" src/app src/components  # Umlaut-gate expect zero',
    );
  }
  if (config.compliance.dsgvo_kit) {
    lines.push(
      '# DSGVO PII-check (no PII in profiles table)',
      'grep -rn "email\\|phone\\|birth_date" supabase/migrations/*profiles* 2>/dev/null | grep -v "auth\\.users" | grep -v "comment"',
      '# expect: zero matches',
    );
  }
  if (config.localization.locales.length > 1) {
    lines.push(
      'npm run i18n:check              # expect keys match across all locales',
    );
  }
  lines.push(
    '# No unsubstituted placeholders anywhere',
    'grep -rn "{{" src/ supabase/migrations/ messages/ 2>/dev/null | grep -v "node_modules"  # expect zero',
    'npm run build   # inspect .next/analyze/ target: first-load < 300KB',
    '```',
  );

  return lines.join('\n');
}

export function renderDsgvoChecklist(config: AegisConfig): string | null {
  if (config.compliance.dsgvo_kit !== true) return null;
  return [
    '# DSGVO Checklist (verify post-build)',
    '',
    '- [ ] Cookie-banner shows on first-visit in incognito',
    '- [ ] `/datenschutz` and `/impressum` render with real company-info (no `{{placeholders}}`)',
    '- [ ] `/api/dsgvo/export` returns user\'s data as JSON download',
    '- [ ] `/api/dsgvo/delete` creates `deletion_queue` row with `scheduled_for = now + 30d`',
    '- [ ] `profiles` table has NO email / phone columns (email lives in `auth.users`)',
    '- [ ] Every sensitive action creates an `audit_log` row',
    '- [ ] Every log call uses `logger.*`, not `console.*` (spot-grep: `grep -rn "console\\." src/`)',
    '- [ ] `pg_cron` scheduled for `process_deletion_queue()` (verify: `SELECT * FROM cron.job`)',
    '- [ ] Audit-log is append-only (try UPDATE / DELETE, should fail)',
  ].join('\n');
}

export function renderEnvVars(
  config: AegisConfig,
  patterns: readonly LoadedPattern[],
): string {
  const lines: string[] = [
    '# Environment Variables',
    '',
    'Create `.env.local` (copy-paste template, fill project-specific values):',
    '',
    '```env',
    '# ----------------------------------------------------------------------------',
    '# Supabase (required)',
    '# ----------------------------------------------------------------------------',
    'NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ...',
    'SUPABASE_SERVICE_ROLE_KEY=eyJ...     # SERVER-SIDE ONLY, never expose to client',
    '',
    '# ----------------------------------------------------------------------------',
    '# App config',
    '# ----------------------------------------------------------------------------',
    'NEXT_PUBLIC_APP_URL={{PRODUCTION_URL}}',
    'DEFAULT_TENANT_ID={{DEFAULT_TENANT_ID}}',
    'TRUSTED_PROXY_COUNT=1                 # 1 for Dokploy / Vercel, 2 for Cloudflare-in-front',
  ];

  if (patterns.some((p) => p.frontmatter.name === 'dsgvo-kit')) {
    lines.push(
      'CONSENT_VERSION=2026-04-23-v1          # bump when T&C changes',
    );
  }
  if (patterns.some((p) => p.frontmatter.name === 'logger-pii-safe')) {
    lines.push(
      'ENCRYPTION_KEY=0af1b2c3d4...64-hex-chars   # openssl rand -hex 32 (if encrypted-at-rest fields)',
    );
  }

  if (config.email.provider !== 'skip') {
    lines.push(
      '',
      '# ----------------------------------------------------------------------------',
      '# SMTP (required for transactional email)',
      '# ----------------------------------------------------------------------------',
      'SMTP_HOST=smtp.example.com',
      'SMTP_PORT=587',
      'SMTP_USER=noreply@example.com',
      'SMTP_PASS=your-smtp-password',
      'SMTP_FROM_NAME={{APP_NAME}}',
      'SMTP_FROM_ADDRESS=noreply@example.com',
    );
  }
  lines.push('```', '', 'Create `.env.production.example` matching this structure (without secrets) for deploy-docs.');

  return lines.join('\n');
}

export function renderPostBuildReportTemplate(): string {
  return [
    '# Post-Build Report',
    '',
    'When complete, create `POST-BUILD-REPORT.md` with the following structure:',
    '',
    '- Agent name plus version',
    '- Completion timestamp plus total build time',
    '- Commits list (one per phase)',
    '- Quality-gate results table',
    '- Features-delivered checklist',
    '- Known limitations plus follow-ups',
    '- How-to-deploy summary matching the chosen deployment target',
    '- User-actions-needed list (Supabase dashboard, pg_cron, SMTP, legal review)',
    '- Cost summary (optional)',
  ].join('\n');
}

export function renderFooter(
  config: AegisConfig,
  patterns: readonly LoadedPattern[],
): string {
  return [
    '---',
    '',
    '**END OF AGENT BRIEF.**',
    '',
    'Agent: start with Phase 1 now. Re-read the Core Rules section before writing any code. Flag any ambiguity to user before proceeding. Good luck.',
    '',
    '---',
    '',
    '# Meta (for reference, skip unless debugging)',
    '',
    '**Pattern versions included:**',
    ...patterns.map(
      (p) => `- ${p.frontmatter.category}/${p.frontmatter.name} v${p.frontmatter.version}`,
    ),
    '',
    '**Brief-generation config:**',
    `- Tone: ${config.brief_options.tone}`,
    `- Lang: ${config.brief_options.lang}`,
    `- Target agent: ${config.brief_options.target_agent}`,
    '',
    `**Quality-target:** score >= 960 / grade A / 0 critical. If a brief-guided-build falls below this, file a pattern-defect issue with the generated brief plus the \`aegis scan\` output.`,
  ].join('\n');
}
