export * from './types.js';
export { detectStack } from './detect.js';
export { calculateScore, getGrade, getBadge, CATEGORY_WEIGHTS } from './scoring.js';
export { loadConfig, type ConfigFileShape } from './config.js';
export { Orchestrator } from './orchestrator.js';
export { exec, commandExists, walkFiles, readFileSafe, clearWalkFilesCache, getChangedFiles, type ExecResult, type ExecOptions } from './utils.js';
export { getVersion } from './version.js';
export { isTestFile } from './is-test-path.js';
export {
  parseSuppressions,
  isSuppressed,
  getUnusedSuppressions,
  getNakedSuppressions,
  type Suppression,
} from './suppressions.js';
export {
  globToRegex,
  configSuppressionMatches,
  applyPipelineSuppressions,
  type SuppressionStats,
} from './suppression-filter.js';
export {
  PRECISION_GATES,
  SCANNER_TIERS,
  tierOf,
  gateFor,
  passesPrecisionGate,
  type PrecisionTier,
} from './precision-tiers.js';
export {
  RoESchema,
  validateTargetInScope,
  validateTemporalEnvelope,
  getAssetCriticality,
  validateAction,
  synthesizeMinimalRoE,
  loadRoE,
  type RoE,
  type ValidationDecision,
  type RoEParseResult,
  type RoEParseSuccess,
  type RoEParseFailure,
} from './roe/index.js';
export {
  emitEvent,
  makeEvent,
  findingEvent,
  isCriticalSeverity,
  initStateFile,
  EngagementStateSchema,
  writeEngagementState,
  loadEngagementState,
  newEngagementState,
  installSignalHandlers,
  dispatchNotification,
  sha256,
  canonicalize,
  hashCanonical,
  ChainedEmitter,
  verifyAuditChain,
  opsecPace,
  applyOpsecHeaders,
  _resetOpsecPacingForTesting,
  type EngagementEvent,
  type EngagementEventBase,
  type EventSink,
  type EngagementState,
  type LoadStateResult,
  type LoadStateOk,
  type LoadStateFailure,
  type DumpReason,
  type SignalHandlerOptions,
  type NotificationConfig,
  type ChainedEmitterOpts,
  type ChainVerifyResult,
  type ChainVerifyOk,
  type ChainVerifyFailure,
  type OpsecOptions,
} from './runtime/index.js';
export {
  assignCiaVector,
  evaluateCiaThreshold,
  CWE_CIA_DEFAULTS,
  evaluateApprovalGate,
  detectIrreversibleActions,
  evaluateIrreversibleGate,
  PHASE_TO_AUTONOMY_LEVEL,
  validateDelegationMatrix,
  rolesForAction,
  escalateOnSeverity,
  escalateOnConfidence,
  escalateOnComplianceTrigger,
  type CiaThresholdEvaluation,
  type AutonomyLevel,
  type AutonomyLevelPolicy,
  type AutonomyLevelsConfig,
  type ApprovalGateDecision,
  type IrreversibleGateDecision,
  type DelegationEntry,
  type AuthorityMatrixValidation,
  type SeverityEscalationConfig,
  type ConfidencePauseConfig,
  type ComplianceTriggerConfig,
  type EscalationDecision,
} from './oversight/index.js';
export {
  startKillRequestWatcher,
  requestKill,
  startDeadManHeartbeat,
  runHealthCheck,
  newHealthCounters,
  currentHeapMb,
  errorRate,
  probeTargetIntegrity,
  detectScopeBreach,
  withPhaseTimeout,
  derivePhaseTimeoutMs,
  type KillRequestWatcherOptions,
  type KillRequestWatcherHandle,
  type HeartbeatOptions,
  type HeartbeatHandle,
  type HealthThresholds,
  type HealthCounters,
  type HealthCheckResult,
  type IntegrityProbeBaseline,
  type IntegrityProbeResult,
  type IntegrityProbeOptions,
  type FindingLike,
  type BreachDetectionResult,
  type TimeoutResult,
  type TimeoutOk,
  type TimeoutFailure,
  type PhaseTimeoutOptions,
} from './safety-controls/index.js';
export {
  enforceInstructionBoundary,
  WRAPPER_ACTION_ALLOWLIST,
  validateWrapperResponse,
  detectAuthorityClaim,
  pinConfig,
  verifyConfig,
  safeFetch,
  classifyIp,
  isSafeFetchRejection,
  detectScopeExpansion,
  composeEgressAllowlist,
  withEgressEnv,
  ORCHESTRATOR_ESSENTIALS,
  validateSandboxMode,
  wrapForSandbox,
  preflightSandboxImages,
  SANDBOX_MODES,
  DEFAULT_WRAPPER_IMAGES,
  type WrapperAction,
  type ResponseValidation,
  type AuthorityClaim,
  type AuthorityClaimResult,
  type ConfigPin,
  type ConfigVerifyResult,
  type SafeFetchOptions,
  type SafeFetchRejection,
  type SafeFetchRejectReason,
  type ScopeExpansionKind,
  type ScopeExpansionResult,
  type EgressAllowlist,
  type ComposeEgressAllowlistOptions,
  type SandboxMode,
  type SandboxModeValidation,
  type WrapForSandboxOptions,
  type WrappedExec,
  type SandboxPreflightResult,
  type PreflightSandboxOptions,
} from './manipulation-resistance/index.js';
