#!/usr/bin/env bash
# Phase 10: Fresh Vibecoded Target Hunt + AEGIS-Scan
# 2026-04-29 — RideMatch1/AEGIS bounty pipeline
#
# Searches GitHub for fresh, low-star, vibecoded Next.js + Supabase repos,
# clones top candidates, runs AEGIS scan, surfaces high-severity findings.

set -uo pipefail

WORKDIR="$HOME/findings/vibecoded-fresh-$(date +%Y%m%d)"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AEGIS_CLI="$REPO_ROOT/packages/cli/dist/index.js"
mkdir -p "$WORKDIR/clones" "$WORKDIR/scans"
cd "$WORKDIR"

if [ ! -f "$AEGIS_CLI" ]; then
  echo "error: AEGIS CLI not built at $AEGIS_CLI" >&2
  exit 1
fi

echo "🔍 Hunt-targets: vibecoded Next.js + Supabase, low-star, recent"
echo "  Workdir: $WORKDIR"
echo ""

# Multiple parallel queries — each surfaces a different vibecoded-signal.
# Dedupe at the end via sort -u.
> raw-targets.txt

run_query() {
  local label="$1"
  local query="$2"
  echo "── query [$label]"
  gh search repos "$query" \
    --limit 30 \
    --json url,fullName,stargazersCount,pushedAt \
    --jq '.[] | [.fullName, (.stargazersCount|tostring), .pushedAt, .url] | @tsv' \
    2>/dev/null >> raw-targets.txt
}

# Q1: explicit vibecoded markers + Supabase
run_query "bolt+supabase" '"built with bolt" supabase pushed:>2026-04-01 language:TypeScript'
run_query "v0+supabase"   '"v0.dev" supabase pushed:>2026-04-01 language:TypeScript'
run_query "lovable+sb"    '"lovable" supabase pushed:>2026-04-01 language:TypeScript'
run_query "cursor+sb"     '"generated by cursor" supabase pushed:>2026-04-01 language:TypeScript'

# Q2: SaaS-starter-kit forks (low star = recent fork)
run_query "saas-kit"      'supabase next.js "saas" stars:<50 pushed:>2026-04-15 language:TypeScript'

# Q3: hidden gold — service_role + low review (likely missing RLS)
run_query "svcrole-leak"  '"service_role" "@supabase/ssr" stars:<30 pushed:>2026-04-01 language:TypeScript'

# Q4: Next.js + supabase migrations on tiny repos (high RLS-bug rate)
run_query "migrations"    'path:supabase/migrations supabase next stars:<30 pushed:>2026-04-15'

# Dedupe by repo fullname
echo ""
echo "── dedupe + filter"
sort -u -k1,1 raw-targets.txt | head -25 > targets.txt
TOTAL=$(wc -l < targets.txt | tr -d ' ')
echo "  Unique candidates: $TOTAL"
echo ""

if [ "$TOTAL" -eq 0 ]; then
  echo "⚠ No targets found. Adjusting queries needed."
  exit 0
fi

# Print the target list
echo "── targets (top 25, sorted unique)"
awk -F'\t' '{printf "  %-50s %4s★  %s\n", $1, $2, $3}' targets.txt
echo ""

# Clone + scan top-15 (or all if fewer)
LIMIT=15
echo "── clone + AEGIS-scan top-$LIMIT"
COUNT=0
while IFS=$'\t' read -r fullname stars pushedAt url; do
  COUNT=$((COUNT+1))
  if [ "$COUNT" -gt "$LIMIT" ]; then break; fi

  # Flatten repo name to safe filename (owner_name)
  safe_name="${fullname//\//_}"
  clone_dir="$WORKDIR/clones/$safe_name"
  scan_out="$WORKDIR/scans/$safe_name.json"

  echo ""
  echo "── [$COUNT/$LIMIT] $fullname (★$stars, pushed $pushedAt)"

  if [ ! -d "$clone_dir" ]; then
    git clone --depth=1 --quiet "$url" "$clone_dir" 2>&1 | sed 's/^/    /' || {
      echo "    ✗ clone failed, skip"
      continue
    }
  fi

  start_time=$(date +%s)
  if node "$AEGIS_CLI" scan "$clone_dir" --format json > "$scan_out" 2> "$scan_out.err"; then
    elapsed=$(( $(date +%s) - start_time ))
    findings=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).findings.length)" 2>/dev/null)
    blocked=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).blocked ? '[BLOCKED]' : '')" 2>/dev/null)
    score=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).score)" 2>/dev/null)
    grade=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).grade)" 2>/dev/null)
    echo "    ✓ score:$score grade:$grade findings:$findings ${blocked} (${elapsed}s)"
    rm -f "$scan_out.err"
  else
    elapsed=$(( $(date +%s) - start_time ))
    # exit-1 = blocker-severity, still valid output
    if [ -s "$scan_out" ] && node -e "JSON.parse(require('fs').readFileSync('$scan_out'))" 2>/dev/null; then
      findings=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).findings.length)" 2>/dev/null)
      score=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).score)" 2>/dev/null)
      grade=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).grade)" 2>/dev/null)
      echo "    ✓ score:$score grade:$grade findings:$findings [BLOCKED] (${elapsed}s)"
      rm -f "$scan_out.err"
    else
      echo "    ✗ scan failed (${elapsed}s)"
      head -5 "$scan_out.err" 2>/dev/null | sed 's/^/      /'
    fi
  fi
done < targets.txt

echo ""
echo "🎉 Phase 10 done. Triage with:"
echo "    ls $WORKDIR/scans/"

# Opt-in auto-cleanup (battle-testing directive: wipe clones after triage).
# Default: keep clones so manual finding-verification (Read file:line) is
# possible. Set AEGIS_HUNT_CLEANUP_AFTER=1 to wipe clones immediately.
# For "wipe everything later" use: bash scripts/cleanup-findings.sh
if [ "${AEGIS_HUNT_CLEANUP_AFTER:-0}" = "1" ]; then
  echo ""
  echo "🧹 AEGIS_HUNT_CLEANUP_AFTER=1 — wiping clones (scans kept)"
  rm -rf "$WORKDIR/clones"
  echo "   wiped: $WORKDIR/clones"
  echo "   kept:  $WORKDIR/scans/ (small JSON, no third-party code)"
fi
