#!/usr/bin/env bash
# Phase 10-Crypto: Web3/DeFi/Wallet vibecoded hunt
# Targets: privateKey/mnemonic/seedPhrase leaks in fresh vibecoded crypto SaaS
# 2026-04-29 — local battle-testing, NO outreach

set -uo pipefail

WORKDIR="$HOME/findings/crypto-vibecoded-$(date +%Y%m%d)"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AEGIS_CLI="$REPO_ROOT/packages/cli/dist/index.js"
mkdir -p "$WORKDIR/clones" "$WORKDIR/scans"
cd "$WORKDIR"

if [ ! -f "$AEGIS_CLI" ]; then
  echo "error: AEGIS CLI not built at $AEGIS_CLI" >&2
  exit 1
fi

echo "🔐 Crypto-vibecoded hunt: privateKey/mnemonic/wallet leak surface"
echo "   Workdir: $WORKDIR"
echo ""

> raw-targets.txt
run_query() {
  local label="$1"; local query="$2"
  echo "── query [$label]"
  gh search repos "$query" \
    --limit 30 \
    --json url,fullName,stargazersCount,pushedAt \
    --jq '.[] | [.fullName, (.stargazersCount|tostring), .pushedAt, .url] | @tsv' \
    2>/dev/null >> raw-targets.txt
}

# Q1: vibecoded markers + crypto keywords (LO's brief)
run_query "vibe+crypto-1"  '"built with bolt" wallet pushed:>2026-03-01 language:TypeScript'
run_query "vibe+crypto-2"  '"v0.dev" web3 pushed:>2026-03-01 language:TypeScript'
run_query "vibe+crypto-3"  '"lovable" crypto pushed:>2026-03-01 language:TypeScript'
run_query "vibe+crypto-4"  '"generated by cursor" defi pushed:>2026-03-01 language:TypeScript'

# Q2: secret-leak smoke signals
run_query "privatekey"     'privateKey wallet "next" stars:<80 pushed:>2026-03-15 language:TypeScript'
run_query "mnemonic"       'mnemonic seedphrase "next" stars:<80 pushed:>2026-03-15'
run_query "seedphrase"     '"seed phrase" supabase stars:<50 pushed:>2026-03-01'

# Q3: Web3 stack signals
run_query "viem+sb"        'viem supabase stars:<50 pushed:>2026-04-01 language:TypeScript'
run_query "wagmi+sb"       'wagmi supabase stars:<50 pushed:>2026-04-01 language:TypeScript'
run_query "ethers+sb"      'ethers.js supabase stars:<50 pushed:>2026-04-01 language:TypeScript'
run_query "siwe+sb"        'siwe supabase stars:<60 pushed:>2026-03-01 language:TypeScript'

# Q4: hackathon / defi-MVP indicators
run_query "defi-mvp"       'defi mvp stars:<30 pushed:>2026-04-01 language:TypeScript'
run_query "wallet-saas"    'wallet saas next.js stars:<30 pushed:>2026-04-01'

echo ""
echo "── dedupe + filter"
sort -u -k1,1 raw-targets.txt | head -30 > targets.txt
TOTAL=$(wc -l < targets.txt | tr -d ' ')
echo "  Unique candidates: $TOTAL"
echo ""

if [ "$TOTAL" -eq 0 ]; then
  echo "⚠ No targets found."
  exit 0
fi

echo "── targets (top 30, sorted unique)"
awk -F'\t' '{printf "  %-55s %4s★  %s\n", $1, $2, $3}' targets.txt
echo ""

LIMIT=15
echo "── clone + AEGIS-scan top-$LIMIT"
COUNT=0
while IFS=$'\t' read -r fullname stars pushedAt url; do
  COUNT=$((COUNT+1))
  if [ "$COUNT" -gt "$LIMIT" ]; then break; fi

  safe_name="${fullname//\//_}"
  clone_dir="$WORKDIR/clones/$safe_name"
  scan_out="$WORKDIR/scans/$safe_name.json"

  echo ""
  echo "── [$COUNT/$LIMIT] $fullname (★$stars, $pushedAt)"

  if [ ! -d "$clone_dir" ]; then
    git clone --depth=1 --quiet "$url" "$clone_dir" 2>&1 | sed 's/^/    /' || {
      echo "    ✗ clone failed, skip"; continue;
    }
  fi

  start=$(date +%s)
  if node "$AEGIS_CLI" scan "$clone_dir" --format json > "$scan_out" 2> "$scan_out.err"; then
    elapsed=$(( $(date +%s) - start ))
  else
    elapsed=$(( $(date +%s) - start ))
    if [ ! -s "$scan_out" ] || ! node -e "JSON.parse(require('fs').readFileSync('$scan_out'))" 2>/dev/null; then
      echo "    ✗ scan failed (${elapsed}s)"
      head -3 "$scan_out.err" 2>/dev/null | sed 's/^/      /'
      continue
    fi
  fi

  findings=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).findings.length)" 2>/dev/null || echo "?")
  score=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).score)" 2>/dev/null || echo "?")
  grade=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).grade)" 2>/dev/null || echo "?")
  blocked=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$scan_out')).blocked ? '[BLOCKED]' : '')" 2>/dev/null || echo "")
  echo "    ✓ score:$score grade:$grade findings:$findings $blocked (${elapsed}s)"
  rm -f "$scan_out.err"
done < targets.txt

echo ""
echo "🎉 Crypto hunt done."
echo "   Scans: $WORKDIR/scans/"

# Opt-in auto-cleanup (battle-testing directive: wipe clones after triage).
# Default: keep clones so manual finding-verification (Read file:line) is
# possible. Set AEGIS_HUNT_CLEANUP_AFTER=1 to wipe clones immediately.
# For "wipe everything later" use: bash scripts/cleanup-findings.sh
if [ "${AEGIS_HUNT_CLEANUP_AFTER:-0}" = "1" ]; then
  echo ""
  echo "🧹 AEGIS_HUNT_CLEANUP_AFTER=1 — wiping clones (scans kept)"
  rm -rf "$WORKDIR/clones"
  echo "   wiped: $WORKDIR/clones"
  echo "   kept:  $WORKDIR/scans/ (small JSON, no third-party code)"
fi
